### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by fravaccaro** [dysk0/harbour-pingviini#2]
I'm not sure whether I should upload it here or fork the project and perform a merge request. 

In the meanwhile, here's my first translation for Pingviini. 

Br

[harbour-pingviini-it.ts.txt](https://github.com/dysk0/harbour-pingviini/files/1035878/harbour-pingviini-it.ts.txt)

**Comment by dysk0** [comment]
It would be better to fork the project and perform a merge request. :) but if it is a trouble, I will handle it.

**Comment by fravaccaro** [comment]
Done :)

I suggest you to take a look at Transifex, it's free for oss projects :)

**Comment by dysk0** [comment]
It is added there :)
https://www.transifex.com/gmax/pingviini/
